### PR TITLE
Upgrade Linter dependencies

### LINKED ISSUE #285: Upgrade Linter dependencies
Updates for stylelint and ESLint. 

From ncu: 

```
 eslint                                                 3.6.1  →         3.8.1
 eslint-plugin-import                         2.0.0  →         2.0.1
 eslint-plugin-jsx-a11y                       2.2.2  →         2.2.3
 eslint-plugin-react                           6.3.0  →         6.4.1

 stylelint                                              7.3.1  →         7.5.0
 stylelint-config-standard                 13.0.2  →        14.0.0
```

Should be tested against starter-kyts to make sure everything still works. (Bonus points for additional e2e  or unit tests!)

### PR DESCRIPTION
**Pull request by athos-ribeiro**
- Closes #285

### CODE REVIEW

**Comment by delambo** [comment]
I think we should bump the import plugin down to 1.16.0 for now. Thanks for #290.

**Comment by delambo** [comment]
@athos-ribeiro I'd like to get this in, do you have a sec to update this pull per my comment?

**Comment by athos-ribeiro** [comment]
Done :)

**Comment by delambo** [comment]
Thanks @athos-ribeiro!

**Pull request merged**
