### PR TITLE
babel-preset-latest => babel-preset-env

### LINKED ISSUE #312: Explore babel-preset-env
With #255 we now have `babel-polyfill` in place both on the client and server for necessary ES6+ support. In the case of the client, relatively modern browsers don't need the entire polyfill, and for the server since node 6 is already a pre-req for kyt, most of the polyfill is also unnecessary there.

Although it's arguably still early for [babel-preset-env](https://github.com/babel/babel-preset-env), I think it might be good to experiment with it and see if we can use it to polyfill only what's necessary for newer browsers in the client bundle and node 6+ in the server bundle.

### PR DESCRIPTION
**Pull request by tizmagik**
Closes #312 

Still todo for this PR:

- [ ] should use `"node":"current"` babel target setting for server build ([docs](https://github.com/babel/babel-preset-env#support-a-target-option-node-current-to-compile-for-the-currently-running-node-version))
- [ ] add note about browser targets for userland babel configs

cc @jaredmcdonald

### CODE REVIEW

**Comment by c0b** [comment]
coming from #356 I'm not sure how to use this PR if I merge it locally; as the docs mentioned I have created a .babelrc but it seems kyt is not honoring it

**Comment by tizmagik** [comment]
Ah, sorry for the confusion. The latest kyt on npm (0.3.0) does not honor a local .babelrc -- that will happen in 0.4.0 (which is what master reflects currently). For now, you'll need to manually override babel settings in modifyWebpackConfig() in kyt.config.js

**Comment by delambo** [comment]
@tizmagik - Would it be safe to merge this as-is and followup with the other tasks?

**Comment by tizmagik** [comment]
Yea maybe, let me see what's going on with the tests

**Comment by tizmagik** [comment]
Closing in favor of #531

**Pull request closed without merging**
