### PR TITLE
Fixes loaderUtils.parseQuery() deprecation warning coming from Webpack

### PR DESCRIPTION
**Pull request by janhoogeveen**
Main issue we're trying to solve here:
https://github.com/NYTimes/kyt/issues/407

Related reading:
- https://github.com/webpack/loader-utils/issues/56
- https://github.com/babel/babel-loader/releases/tag/v7.0.0

Should be a straightforward PR. I've tested the changes locally and there's no more errors in my logs!

### CODE REVIEW

**Comment by ccpricenytimes** [comment]
Hi @janhoogeveen thanks for making these changes! I'd like to include this as part of our next larger release, would you mind moving the changelog into the `Master` section and reverting the package.json version bump?

**Comment by janhoogeveen** [comment]
Hy @ccpricenytimes, absolutely. Will do it somewhere today.

**Comment by janhoogeveen** [comment]
@ccpricenytimes All should be ok now, it's up to date with upstream and the only 2 changes are the version bumps for babel-loader and css-loader.

**Comment by delambo** [comment]
@janhoogeveen sorry to get to this so late! I suspect that merging is blocked because the yarn files have conflicts. Instead of making you do more work to update this PR, I think I'm going to close this in favor of #482 which updates webpack and the loaders. Then we'll get all of the babel libraries in a future update, hopefully soon.

🙏

**Pull request closed without merging**
