### PR TITLE
Adds rfc template

### PR DESCRIPTION
**Pull request by delambo**
We're testing a new rfc process in github Issues. So far the idea is to copy and use the rfc template from the Rust repository. We plan on working out the details for the process - how are rfcs labeled, what are their various stages, how are they accepted - as we roll out the first couple proposals.

Feel free to leave ideas here about the initial rfc process. I'll open an Issue so that we can further discuss the final process.

### CODE REVIEW

**Comment by tizmagik** [comment]
Consider [issue templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

**Comment by delambo** [comment]
I'm not exactly sure how issue templates work, but from what I gather the text in the ISSUE_TEMPLATE is inserted into every new issue. If that's right, I'd prefer to leave it in a standalone file for now since I'd like to reserve rfcs for big stuff.

**Comment by tizmagik** [comment]
Right, but you don't have to insert the entire RFC template in the issue template, you can just point folks to it during issue creation behind HTML comment tags (so they don't show up in the actual issue). So, for example, something like this:

```
<!--
    Writing an RFC?: Please use the template in rfc/template.md

    Writing a bug report/feature request?: Please fill in the following fields:
-->    

### Versions of kyt, node, OS

### Bug or Feature?

### Current Behavior

### Desired Behavior
```

And so on...

**Comment by delambo** [comment]
Ah, got ya.

**Comment by delambo** [comment]
Got the issue template in: https://github.com/NYTimes/kyt/pull/317

**Pull request merged**
